# Generated by Django 2.1 on 2018-12-23 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=True, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
